version: '3'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 'password123'
      MYSQL_USER: devuser
      MYSQL_PASSWORD: devpassword
      MYSQL_ROOT_HOST: '%'
    volumes:
      - ./mysql-data:/var/lib/mysql
      - ./sql:/docker-entrypoint-initdb.d
    ports:
      - '3306:3306'
    command: --default-authentication-plugin=mysql_native_password
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: api
    depends_on:
      - mysql
    environment:
      - PORT=${PORT}
      - NODE_ENV=${NODE_ENV}
      - TYPEORM_CONNECTION=${TYPEORM_CONNECTION}
      - TYPEORM_HOST=mysql
      - TYPEORM_PORT=${TYPEORM_PORT}
      - TYPEORM_USERNAME=${TYPEORM_USERNAME}
      - TYPEORM_PASSWORD=${TYPEORM_PASSWORD}
      - TYPEORM_DATABASE=${TYPEORM_DATABASE}
      - TYPEORM_LOGGER=${TYPEORM_LOGGER}
      - TYPEORM_LOGGING=${TYPEORM_LOGGING}
      - TYPEORM_SYNCHRONIZE=${TYPEORM_SYNCHRONIZE}
      - TYPEORM_SSL=${TYPEORM_SSL}
      - JWT_SECRET=${JWT_SECRET}
      - JWT_EXPIRES_IN=${JWT_EXPIRES_IN}
      - JWT_GLOBAL=${JWT_GLOBAL}
      - TICKET_SECRET=${TICKET_SECRET}
    ports:
      - '3000:3000'
    volumes:
      - .:/app
      - /app/node_modules
    command: sh -c "yarn install && yarn start:dev"

    
